
services:
  baumkataster:
    build: .
    container_name: baumkataster-app
    restart: always
    ports:
      - "8085:80" # Port auf 8085 ge√§ndert, um Konflikte zu vermeiden
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
